In [1]:
import torchvision

train_data = torchvision.datasets.CIFAR100('datasets/', train=True, download=True)

100%|██████████████████████████████████████████████████████████████| 169001437/169001437 [00:12<00:00, 13551554.61it/s]


Extracting datasets/cifar-100-python.tar.gz to datasets/


In [3]:
torchvision.datasets.Flowers102('datasets/', download=True)

100%|███████████████████████████████████████████████████████████████| 344862509/344862509 [00:37<00:00, 9255690.27it/s]


Extracting datasets\flowers-102\102flowers.tgz to datasets\flowers-102


100%|████████████████████████████████████████████████████████████████████████████| 502/502 [00:00<00:00, 501797.09it/s]


100%|██████████████████████████████████████████████████████████████████████| 14989/14989 [00:00<00:00, 14990086.47it/s]


Dataset Flowers102
    Number of datapoints: 1020
    Root location: datasets/
    split=train

In [5]:
from scipy import io

iomat_file = io.loadmat('datasets/flowers-102/imagelabels.mat')

In [11]:
iomat_file

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNX86, Created on: Thu Feb 19 15:43:33 2009',
 '__version__': '1.0',
 '__globals__': [],
 'labels': array([[77, 77, 77, ..., 62, 62, 62]], dtype=uint8)}

In [10]:
len(iomat_file['labels'][0])

8189

In [15]:
iomat_file['labels'][0] - 1

array([76, 76, 76, ..., 61, 61, 61], dtype=uint8)

In [12]:
import numpy as np

np.unique(iomat_file['labels'])

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102], dtype=uint8)

In [18]:
torchvision.datasets.Flowers102('datasets/valid/', split='val', download=True)

100%|███████████████████████████████████████████████████████████████| 344862509/344862509 [00:41<00:00, 8231129.19it/s]


Extracting datasets\valid\flowers-102\102flowers.tgz to datasets\valid\flowers-102


100%|████████████████████████████████████████████████████████████████████████████| 502/502 [00:00<00:00, 502156.12it/s]


100%|██████████████████████████████████████████████████████████████████████| 14989/14989 [00:00<00:00, 14993661.50it/s]


Dataset Flowers102
    Number of datapoints: 1020
    Root location: datasets/valid/
    split=val

In [19]:
torchvision.datasets.Flowers102('datasets/test/', split='test', download=True)

100%|███████████████████████████████████████████████████████████████| 344862509/344862509 [00:41<00:00, 8331992.11it/s]


Extracting datasets\test\flowers-102\102flowers.tgz to datasets\test\flowers-102


100%|████████████████████████████████████████████████████████████████████████████| 502/502 [00:00<00:00, 502036.39it/s]


100%|███████████████████████████████████████████████████████████████████████| 14989/14989 [00:00<00:00, 7494149.80it/s]


Dataset Flowers102
    Number of datapoints: 6149
    Root location: datasets/test/
    split=test

In [35]:
iomat_file = io.loadmat('datasets/flowers-102/train/setid.mat')

In [36]:
iomat_file

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNX86, Created on: Thu Feb 19 17:38:58 2009',
 '__version__': '1.0',
 '__globals__': [],
 'trnid': array([[6765, 6755, 6768, ..., 8026, 8036, 8041]], dtype=uint16),
 'valid': array([[6773, 6767, 6739, ..., 8028, 8008, 8030]], dtype=uint16),
 'tstid': array([[6734, 6735, 6737, ..., 8044, 8045, 8047]], dtype=uint16)}

In [37]:
len(iomat_file['trnid'][0])

1020

In [38]:
len(iomat_file['valid'][0])

1020

In [39]:
len(iomat_file['tstid'][0])

6149

In [40]:
torchvision.datasets.Flowers102('datasets/flowers-102/train/', split='train', download=True)

100%|███████████████████████████████████████████████████████████████| 344862509/344862509 [00:37<00:00, 9151111.31it/s]


Extracting datasets\flowers-102\train\flowers-102\102flowers.tgz to datasets\flowers-102\train\flowers-102


100%|████████████████████████████████████████████████████████████████████████████| 502/502 [00:00<00:00, 251048.12it/s]


100%|██████████████████████████████████████████████████████████████████████| 14989/14989 [00:00<00:00, 15007978.67it/s]


Dataset Flowers102
    Number of datapoints: 1020
    Root location: datasets/flowers-102/train/
    split=train

In [41]:
iomat_file = io.loadmat('datasets/flowers-102/train/flowers-102/setid.mat')

In [45]:
len(iomat_file['trnid'][0])

1020

In [46]:
iomat_file['trnid'][0]

array([6765, 6755, 6768, ..., 8026, 8036, 8041], dtype=uint16)

In [53]:
iomat_file

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNX86, Created on: Thu Feb 19 17:38:58 2009',
 '__version__': '1.0',
 '__globals__': [],
 'trnid': array([[6765, 6755, 6768, ..., 8026, 8036, 8041]], dtype=uint16),
 'valid': array([[6773, 6767, 6739, ..., 8028, 8008, 8030]], dtype=uint16),
 'tstid': array([[6734, 6735, 6737, ..., 8044, 8045, 8047]], dtype=uint16)}

In [68]:
import os

In [69]:
images = os.listdir('datasets/flowers-102/jpg/')

In [70]:
images = [images[idx-1] for idx in iomat_file['valid'][0]]

In [71]:
images

['image_06773.jpg',
 'image_06767.jpg',
 'image_06739.jpg',
 'image_06749.jpg',
 'image_06763.jpg',
 'image_06740.jpg',
 'image_06761.jpg',
 'image_06747.jpg',
 'image_06738.jpg',
 'image_06754.jpg',
 'image_05138.jpg',
 'image_05101.jpg',
 'image_05114.jpg',
 'image_05100.jpg',
 'image_05123.jpg',
 'image_05120.jpg',
 'image_05118.jpg',
 'image_05116.jpg',
 'image_05132.jpg',
 'image_05104.jpg',
 'image_06630.jpg',
 'image_06638.jpg',
 'image_06647.jpg',
 'image_06646.jpg',
 'image_06612.jpg',
 'image_06644.jpg',
 'image_06640.jpg',
 'image_06645.jpg',
 'image_06639.jpg',
 'image_06631.jpg',
 'image_05663.jpg',
 'image_05658.jpg',
 'image_05678.jpg',
 'image_05648.jpg',
 'image_05654.jpg',
 'image_05674.jpg',
 'image_05672.jpg',
 'image_05635.jpg',
 'image_05651.jpg',
 'image_05684.jpg',
 'image_05211.jpg',
 'image_05178.jpg',
 'image_05168.jpg',
 'image_05166.jpg',
 'image_05185.jpg',
 'image_05169.jpg',
 'image_05204.jpg',
 'image_05179.jpg',
 'image_05192.jpg',
 'image_05162.jpg',


In [72]:
from torchmetrics.classification import Accuracy, AUROC, F1Score, Recall, Precision

In [82]:
# metrics
acc = Accuracy(task='multiclass', num_classes=102, average='micro')
auroc = AUROC(task='multiclass', num_classes=102, average='macro')
f1 = F1Score(task='multiclass', num_classes=102, average='micro')
recall = Recall(task='multiclass', num_classes=102, average='micro')
precision = Precision(task='multiclass', num_classes=102, average='micro')

In [73]:
import torch

In [75]:
test = torch.nn.CrossEntropyLoss()

In [80]:
test(torch.Tensor([[0.1, 0.7, 0.2]]), torch.Tensor([0.]))

RuntimeError: expected scalar type Long but found Float